version: "3"
services:
  node-app:
    container_name: express-node-app-container 
    depends_on:
      - mongo
      - redis
    volumes:
      - ./src:/app/src:ro 
    ports:
      - "2000:2000"
    env_file:
      - ./.env
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  redis:
    image: redis 
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    depends_on:
      - node-app
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
volumes:
  mongo-db: 