version: "3"
services:
  node-app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    volumes:
      - ./src:/app/src:ro 
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "start-dev"]
    